### PR TITLE
Add correct reboot detection for RHEL 8 and 9

### PR DESCRIPTION
**Pull request by jcpunk**
This adds the correct detection bits for RHEL 8 and 9 to lookup pending reboots.

### CODE REVIEW

**Comment by jcpunk** [comment]
I hate to nag, but I'm sure folks other than myself would benefit from this patch.

**Comment by jcpunk** [comment]
With CentOS Stream 10 due out in the next year, I've updated the logic to be more forward compatible.

@albatrossflavour any chance to get this merged in?

**Comment by albatrossflavour** [comment]
Nice fix, and apologies for the delays in getting it merged

**Comment by jcpunk** [comment]
No worries.

Any chance for a new release?

**Comment by albatrossflavour** [comment]
Absolutely, I'm just finishing off some testing on #215 and hope to get a release out by the end of the week.

**Pull request merged**
